package main

import (
	// "./engine"  // 不能用相路径导入 不然出现很诡异的错误！
	"github.com/goodmall/goodmall/cmd/api/gin/engine"

	"github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"

	_ "./docs" // docs is generated by Swag CLI, you have to import it.
)

// @APIVersion 1.0.0
// @APITitle My Cool API
// @APIDescription My API usually works as expected.
// @Contact api@contact.me
// @TermsOfServiceUrl http://google.com/
// @License BSD
// @LicenseUrl http://opensource.org/licenses/BSD-2-Clause
// @BasePath http://host:port/api/
func main() {

	r := engine.GetMainEngine()

	// use ginSwagger middleware to
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.Run() // listen and serve on 0.0.0.0:8080
}
